### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by TomboFry** [TomboFry/BullHacks17#3]
Displays information - **per player** - such as (can display temporary information until we have the fancy systems in place):

- [x] Player position (eg. 1st, 2nd, etc)
- [x] Lap number (eg. "1/3")
- [x] Pickup indicator
- [ ] Speed
-----
- [x] Get values and put them in the correct places (~~requires #4 to be completed~~)

**Comment by toxicwolf** [comment]
No longer blocked on #4.
