### ISSUE TITLE
Track Mechanics

### ISSUE THREAD

**Issue by TomboFry** [TomboFry/BullHacks17#4]
Calculate percentage of the track that the player has traversed around a lap.

Must be able to detect where a lap starts.

- [x] Spline object system
- [x] Kart position tracking
- [x] Lap counting

**Comment by toxicwolf** [comment]
Lap counter currently increments whenever kart goes from spline position >0.95f to <0.05f in one frame. Should add anti-cheating measures (such as requiring a full lap in the forward direction) if time permits.
